CREATE TABLE CARGO (
  ID_CARGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO_CARGO VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID_CARGO)
);

CREATE TABLE ORGAO (
  ID_ORGAO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO_ORGAO VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID_ORGAO)
);

CREATE TABLE SISTEMA (
  ID_SISTEMA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO_SISTEMA VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID_SISTEMA)
);

CREATE TABLE USUARIO (
  NUMERO_CPF VARCHAR(20) BINARY NOT NULL,
  ORGAO_ID_ORGAO INTEGER UNSIGNED NOT NULL,
  CARGO_ID_CARGO INTEGER UNSIGNED NOT NULL,
  NOME_FUNC VARCHAR(255) NOT NULL,
  PRIMARY KEY(NUMERO_CPF),
  INDEX USUARIO_FKIndex1(ORGAO_ID_ORGAO),
  INDEX USUARIO_FKIndex2(CARGO_ID_CARGO)
);

CREATE TABLE USUARIO_SISTEMA (
  USUARIO_NUMERO_CPF VARCHAR(20) BINARY NOT NULL,
  SISTEMA_ID_SISTEMA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(USUARIO_NUMERO_CPF, SISTEMA_ID_SISTEMA),
  INDEX USUARIO_SISTEMA_FKIndex1(USUARIO_NUMERO_CPF),
  INDEX USUARIO_SISTEMA_FKIndex2(SISTEMA_ID_SISTEMA)
);


